FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml ./

RUN pip install --no-cache-dir -e .

ENV PYTHONUNBUFFERED=1
ENV YTSUBMD_ENV=production
ENV C_FORCE_ROOT=1

CMD ["celery", "-A", "workers.celery_app", "worker", "--loglevel=INFO", "-Q", "youtube-submd"]
